default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wstech_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: wstech_test
  username: postgres
  password:

production:
  <<: *default
  database: wstech_production
  username: wstech
  password: <%= ENV['WSTECH_DATABASE_PASSWORD'] %>
